### ISSUE TITLE
Create CI pipeline for this repo

### ISSUE THREAD

**Issue by lourencofsilva** [robota-suite/robota-core#11]
Taking into account the potential for further pull requests, a CI pipeline should be added to ensure automated testing.

**Comment by suzanneEmbury** [comment]
This will be super helpful, @lourencofsilva , I agree.  I look forward to seeing the PR for this!

**Comment by lourencofsilva** [comment]
@suzanneEmbury please see PR above for this. Regarding automated PyPI releases, I see that these are currently being published from the GitLab repo using tags and not GitHub, so it wouldn't make sense to create an action here, correct?

**Comment by suzanneEmbury** [comment]
Thanks for your hard work on this @lourencofsilva .  I'm working on the next code review but am a bit busy with marking and other projects, so my responses (as you've seen) will be a bit delayed.  But I am still working on this and will get back to you as soon as I can.

Regarding your point about deployment from GitLab, you're correct - but we may choose to either keep this repo as a mirror of the GitLab one, and deploy from here - or even, if it gets more active, move to using this repo as the main repo for work on this code base.

But it's fine to leave this for now.  We have enough to be getting on with before we worry about automated upload to PyPI.

**Comment by lourencofsilva** [comment]
No worries at all. I've also been quite busy with exams! That makes sense, will leave as is for now.
