### ISSUE TITLE
Implement Poetry for dependency management

### ISSUE THREAD

**Issue by nigelmj** [robota-suite/robota-core#14]
Considering future enhancements and maintainability, introduce Poetry for robust dependency management.

**Comment by suzanneEmbury** [comment]
It would be great to have better dependency management for this project through Poetry, @Nigel007 .  If you are up for suggesting a starting approach to that through a PR, we would be interested in seeing it.

Please note that it's a busy time of year for us with exams and marking, so I may not be able to look at the PR immediately.  But I will get to it eventually - just expect it to take a couple of weeks, unless you are lucky with your timing.

Thanks again.

**Comment by nigelmj** [comment]
@suzanneEmbury I've made a PR for this. The updated toml file and the auto-generated lock file remove the need for a requirements.txt. This PR also brings automatic updating of the toml file when adding new dependencies.

**Comment by suzanneEmbury** [comment]
Added in PR #16
